In [12]:
import pandas as pd
import matplotlib.pyplot as plot
%matplotlib inline

In [13]:
df = pd.read_csv("prisoners.csv")

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.describe()

In [14]:
sum_of_cols = list(df)
del_columns = ['STATE/UT', 'YEAR']

sum_of_cols = [item for item in sum_of_cols if item not in del_columns]
sum_of_cols

['No. of Inmates benefitted by Elementary Education',
 'No. of Inmates benefitted by Adult Education',
 'No. of Inmates benefitted by Higher Education',
 'No. of Inmates benefitted by Computer Course']

In [15]:
'Create a new column -’total_benefitted’ that is a sum of inmates benefitted through all modes.'

df['total_benefitted'] = df[sum_of_cols].sum(axis = 1)
#df

In [16]:
sum_of_cols.append('total_benefitted')
sum_of_cols

['No. of Inmates benefitted by Elementary Education',
 'No. of Inmates benefitted by Adult Education',
 'No. of Inmates benefitted by Higher Education',
 'No. of Inmates benefitted by Computer Course',
 'total_benefitted']

In [17]:
'Create a new row - “totals” that is the sum of all inmates benefitted through each mode across all states.'
#df_xtemp = df[sum_of_cols].sum(axis = 0)
#df_totals = df.append(df_xtemp, ignore_index=True)

df_totals = df.append(df[sum_of_cols].sum(axis = 0), ignore_index=True)
df_totals

,STATE/UT,YEAR,No. of Inmates benefitted by Elementary Education,No. of Inmates benefitted by Adult Education,No. of Inmates benefitted by Higher Education,No. of Inmates benefitted by Computer Course,total_benefitted
0,Andhra Pradesh,2013.0,9480.0,13758.0,672.0,170.0,24080.0
1,Arunachal Pradesh,2013.0,0.0,0.0,0.0,0.0,0.0
2,Assam,2013.0,676.0,750.0,14.0,30.0,1470.0
3,Bihar,2013.0,1693.0,3013.0,125.0,1417.0,6248.0
4,Chhatisgarh,2013.0,1664.0,1803.0,192.0,103.0,3762.0
5,Goa,2013.0,7.0,0.0,6.0,88.0,101.0
6,Gujarat,2013.0,2310.0,3133.0,875.0,966.0,7284.0
7,Haryana,2013.0,1131.0,774.0,1112.0,243.0,3260.0
8,Himachal Pradesh,2013.0,33.0,80.0,26.0,0.0,139.0
9,Jammu & Kashmir,2013.0,102.0,124.0,33.0,34.0,293.0
10,Jharkhand,2013.0,3008.0,2595.0,138.0,574.0,6315.0
11,Karnataka,2013.0,633.0,568.0,170.0,12.0,1383.0
12,Kerala,2013.0,156.0,96.0,24.0,250.0,526.0
13,Madhya Pradesh,2013.0,1978.0,9574.0,301.0,151.0,12004.0
14,Maharashtra,2013.0,346.0,2743.0,882.0,1330.0,5301.0
15,Manipur,2013.0,0.0,0.0,0.0,0.0,0.0
16,Meghalaya,2013.0,1.0,30.0,0.0,0.0,31.0
17,Mizoram,2013.0,0.0,25.0,18.0,0.0,43.0
18,Nagaland,2013.0,0.0,0.0,0.0,0.0,0.0
19,Orissa,2013.0,622.0,613.0,277.0,384.0,1896.0
20,Punjab,2013.0,325.0,606.0,112.0,168.0,1211.0
21,Rajasthan,2013.0,1050.0,237.0,64.0,38.0,1389.0
22,Sikkim,2013.0,0.0,0.0,0.0,0.0,0.0
23,Tamilnadu,2013.0,68.0,1664.0,757.0,478.0,2967.0
24,Tripura,2013.0,15.0,13.0,4.0,2.0,34.0
25,Uttar Pradesh,2013.0,7876.0,8093.0,1353.0,212.0,17534.0
26,Uttaranchal,2013.0,205.0,42.0,29.0,72.0,348.0
27,West Bengal,2013.0,2023.0,1889.0,123.0,460.0,4495.0
28,A & N Islands,2013.0,167.0,45.0,11.0,0.0,223.0
29,Chandigarh,2013.0,0.0,265.0,85.0,0.0,350.0
30,D & N Haveli,2013.0,0.0,0.0,0.0,0.0,0.0
31,Daman & Diu,2013.0,0.0,0.0,0.0,0.0,0.0
32,Delhi,2013.0,1458.0,1187.0,908.0,174.0,3727.0
33,Lakshadweep,2013.0,0.0,0.0,0.0,0.0,0.0
34,Pondicherry,2013.0,0.0,0.0,0.0,0.0,0.0
35,NaN,NaN,37027.0,53720.0,8311.0,7356.0,106414.0